services:
  - type: web
    name: gerenciador-orcamento
    runtime: python
    runtimeVersion: 3.12
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --port=$PORT wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
